# Generated by Django 4.2.27 on 2026-01-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceData',
        ),
    ]
