# Generated by Django 4.2.27 on 2026-01-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_stocknews'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknews',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocknews',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
