# Generated by Django 4.2.27 on 2026-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatmessage_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='推荐给用户的问题', max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '推荐问题',
                'verbose_name_plural': '推荐问题',
                'ordering': ['created_at'],
            },
        ),
    ]
