# Generated by Django 4.2.27 on 2026-01-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatroom_and_migrate_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': '聊天消息', 'verbose_name_plural': '聊天消息'},
        ),
    ]
