# Generated by Django 4.2.27 on 2026-01-17 13:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0004_stocknews_publish_time_stocknews_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfsWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('window_months', models.PositiveSmallIntegerField(default=6)),
                ('target', models.CharField(default='future_1m_ic', max_length=64)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-as_of', '-created_at'),
                'indexes': [models.Index(fields=['as_of'], name='analysis_ef_as_of_531bf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EfsFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('formula', models.TextField()),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efs_factors', to='markets.stock')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EfsAlphaFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('expression', models.TextField()),
                ('status', models.CharField(default='candidate', max_length=32)),
                ('last_score', models.FloatField(blank=True, null=True)),
                ('last_ic', models.FloatField(blank=True, null=True)),
                ('last_top_return', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'indexes': [models.Index(fields=['status', 'updated_at'], name='analysis_ef_status_d79011_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='markets.stock')),
            ],
        ),
        migrations.CreateModel(
            name='RagDocumentFundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_manual', models.BooleanField(default=False)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_fundamentals', to='markets.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'created_at'], name='analysis_ra_stock_i_498899_idx')],
            },
        ),
        migrations.CreateModel(
            name='RagDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_manual', models.BooleanField(default=False)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_documents', to='markets.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'created_at'], name='analysis_ra_stock_i_4147cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='EfsDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efs_data', to='markets.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'date'], name='analysis_ef_stock_i_475d0d_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EfsAlphaEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('ic', models.FloatField(blank=True, null=True)),
                ('top_return', models.FloatField(blank=True, null=True)),
                ('universe_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='analysis.efsalphafactor')),
            ],
            options={
                'ordering': ('-as_of', '-created_at'),
                'indexes': [models.Index(fields=['factor', 'as_of'], name='analysis_ef_factor__9d3594_idx')],
            },
        ),
    ]
