# Generated by Django 4.2.27 on 2026-01-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_remove_efsalphafactor_scores'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS analysis_efsfactor CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS analysis_efsweight CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RenameIndex(
            model_name='ragdocumentfundamental',
            new_name='analysis_ra_stock_i_498899_idx',
            old_name='analysis_rag_stock_fund_idx',
        ),
        migrations.AlterField(
            model_name='ragdocumentfundamental',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS analysis_efsfactor CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
