# Generated by Django 4.2.27 on 2026-01-19 06:22

from django.db import migrations, models


def add_etf_fields_if_not_exists(apps, schema_editor):
    """Add ETF ranking fields only if they don't exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if etf_rank column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='analysis_analysisresult' AND column_name='etf_rank'
        """)
        if not cursor.fetchone():
            # Add etf_rank field
            cursor.execute("""
                ALTER TABLE analysis_analysisresult 
                ADD COLUMN etf_rank INTEGER NULL
            """)
        
        # Check if etf_universe_size column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='analysis_analysisresult' AND column_name='etf_universe_size'
        """)
        if not cursor.fetchone():
            # Add etf_universe_size field
            cursor.execute("""
                ALTER TABLE analysis_analysisresult 
                ADD COLUMN etf_universe_size INTEGER NULL
            """)
        
        # Check if index exists
        cursor.execute("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE tablename='analysis_analysisresult' AND indexname='analysis_an_etf_ran_14e4fa_idx'
        """)
        if not cursor.fetchone():
            # Add index
            cursor.execute("""
                CREATE INDEX analysis_an_etf_ran_14e4fa_idx 
                ON analysis_analysisresult (etf_rank)
            """)


def reverse_add_etf_fields(apps, schema_editor):
    """Remove ETF ranking fields"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Drop index if exists
        cursor.execute("DROP INDEX IF EXISTS analysis_an_etf_ran_14e4fa_idx")
        # Drop columns if exist
        cursor.execute("ALTER TABLE analysis_analysisresult DROP COLUMN IF EXISTS etf_rank")
        cursor.execute("ALTER TABLE analysis_analysisresult DROP COLUMN IF EXISTS etf_universe_size")


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_add_ranking_fields'),
    ]

    operations = [
        # Note: EfsFactor and EfsWeight models were already deleted in migration 0008
        # Use RunPython to safely add ETF ranking fields only if they don't exist
        migrations.RunPython(
            add_etf_fields_if_not_exists,
            reverse_add_etf_fields,
        ),
        # Update stock_rank help_text
        migrations.AlterField(
            model_name='analysisresult',
            name='stock_rank',
            field=models.PositiveIntegerField(blank=True, help_text='股票排名（1-based，基于 overall_score，仅用于股票）', null=True),
        ),
    ]
