# Generated by Django 4.2.27 on 2026-01-19 07:10

from django.db import migrations, models


def add_etf_rank_if_not_exists(apps, schema_editor):
    """Add etf_rank field only if it doesn't exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if etf_rank column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='analysis_analysisresult' AND column_name='etf_rank'
        """)
        if not cursor.fetchone():
            # Add etf_rank field
            cursor.execute("""
                ALTER TABLE analysis_analysisresult 
                ADD COLUMN etf_rank INTEGER NULL
            """)
        
        # Check if index exists
        cursor.execute("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE tablename='analysis_analysisresult' AND indexname='analysis_an_etf_ran_14e4fa_idx'
        """)
        if not cursor.fetchone():
            # Add index
            cursor.execute("""
                CREATE INDEX analysis_an_etf_ran_14e4fa_idx 
                ON analysis_analysisresult (etf_rank)
            """)


def reverse_add_etf_rank(apps, schema_editor):
    """Remove etf_rank field"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Drop index if exists
        cursor.execute("DROP INDEX IF EXISTS analysis_an_etf_ran_14e4fa_idx")
        # Drop column if exists
        cursor.execute("ALTER TABLE analysis_analysisresult DROP COLUMN IF EXISTS etf_rank")


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_remove_efsfactor_stock_delete_efsweight_and_more'),
    ]

    operations = [
        # Note: EfsFactor and EfsWeight models were already deleted in migration 0008
        # We only need to add ETF ranking field here
        migrations.RunPython(
            add_etf_rank_if_not_exists,
            reverse_add_etf_rank,
        ),
        # Update stock_rank help_text
        migrations.AlterField(
            model_name='analysisresult',
            name='stock_rank',
            field=models.PositiveIntegerField(blank=True, help_text='股票排名（1-based，基于 overall_score，仅用于股票）', null=True),
        ),
    ]
