# Generated by Django 4.2.27 on 2026-01-21 12:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_remove_efsfactor_stock_delete_efsweight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_regime', models.CharField(default='Neutral', max_length=32)),
                ('market_cycle', models.CharField(default='Base', max_length=32)),
                ('market_score', models.IntegerField(default=50)),
                ('market_bias', models.IntegerField(default=0)),
                ('market_reason', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddIndex(
            model_name='marketcontext',
            index=models.Index(fields=['-updated_at'], name='analysis_ma_updated_f60f44_idx'),
        ),
    ]
