# Generated by Django 4.2.27 on 2026-01-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_marketcontext_remove_efsfactor_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketcontext',
            name='market_regime',
        ),
    ]
