# Generated by Django 4.2.27 on 2026-01-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_remove_efsfactor_stock_delete_efsweight_and_more'),
    ]

    operations = [
        # Safely remove field from EfsFactor if table exists
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables 
                          WHERE table_schema = 'public' 
                          AND table_name = 'analysis_efsfactor') THEN
                    ALTER TABLE analysis_efsfactor DROP COLUMN IF EXISTS stock_id;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Safely handle EfsWeight deletion (table may already be deleted)
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS analysis_efsweight CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Safely rename indexes if they exist
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Rename index for analysisresult if it exists
                IF EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = 'analysis_an_stock_r_idx'
                ) THEN
                    ALTER INDEX analysis_an_stock_r_idx RENAME TO analysis_an_stock_r_80d751_idx;
                END IF;
                
                -- Rename index for efsalphafactor if it exists
                IF EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = 'analysis_ef_factor__idx'
                ) THEN
                    ALTER INDEX analysis_ef_factor__idx RENAME TO analysis_ef_factor__fbb1d4_idx;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Safely remove fields that may not exist
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Remove stock_universe_size from analysis_analysisresult if it exists
                IF EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'analysis_analysisresult' 
                    AND column_name = 'stock_universe_size'
                ) THEN
                    ALTER TABLE analysis_analysisresult DROP COLUMN stock_universe_size;
                END IF;
                
                -- Remove universe_size from analysis_efsalphaevaluation if it exists
                IF EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'analysis_efsalphaevaluation' 
                    AND column_name = 'universe_size'
                ) THEN
                    ALTER TABLE analysis_efsalphaevaluation DROP COLUMN universe_size;
                END IF;
                
                -- Remove factor_universe_size from analysis_efsalphafactor if it exists
                IF EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'analysis_efsalphafactor' 
                    AND column_name = 'factor_universe_size'
                ) THEN
                    ALTER TABLE analysis_efsalphafactor DROP COLUMN factor_universe_size;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Safely add etf_rank field and index if they don't exist
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Add etf_rank column if it doesn't exist
                IF NOT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'analysis_analysisresult' 
                    AND column_name = 'etf_rank'
                ) THEN
                    ALTER TABLE analysis_analysisresult 
                    ADD COLUMN etf_rank INTEGER NULL;
                END IF;
                
                -- Add index if it doesn't exist
                IF NOT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = 'analysis_an_etf_ran_14e4fa_idx'
                ) THEN
                    CREATE INDEX analysis_an_etf_ran_14e4fa_idx ON analysis_analysisresult (etf_rank);
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Safely handle EfsFactor deletion (table may already be deleted)
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS analysis_efsfactor CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
